using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public static class Localization {
    private static bool isInited;
    private const string EN = "EN";
    private const string TR = "TR";
    private static string lang = EN;
    private static Dictionary<string, Dictionary<string, string>> all;
    private static HashSet<string> errorSet;

    public static void Init() {
        if (isInited) return;
        isInited = true;
        all = new Dictionary<string, Dictionary<string, string>>();
        all.Add(EN, new Dictionary<string, string>() {
            {"MOTHER000", "MY SON!"},
            {"MOTHER001", "Hey mom, what's up?"},
            {"MOTHER002", "MY SON!"},
            {"MOTHER003", "Hey, yeah, what's up?"},
            {"MOTHER004", "Did you bring me my cocaine?"},
            {"MOTHER005", "MOM!"},
            {"MOTHER006", "WHAT? MAMA NEEDS HER COKE!"},
            {"MOTHER007", "It's not funny when you make the same joke for the fifth time."},
            {"MOTHER008", "Well I disagree."},
            {"MOTHER009", "Okay okay. How are you feeling?"},
            {"MOTHER010", "Same. I feel like an old lady. It's not very nice. How are you? How's work?"},
            {"MOTHER011", "Work's fine. It's tiring to make the world a better place."},
            {"MOTHER012", "Police making the world a better place?! Hah!.."},
            {"MOTHER013", "Mom, seriously?! Is that what you think about my job?"},
            {"MOTHER014", "Honey, I love you and I am proud of you."},
            {"MOTHER015", "I find that a bit hard to believe sometimes but okay."},
            {"MOTHER016", "Be respectful to mommy!"},
            {"MOTHER017", "Sorry mom, I love you, too."},

            {"POLICE000", "Hey kid! How have you been? Feeling better?"},
            {"POLICE001", "Thank you sir, much better."},
            {"POLICE002", "Good, good. We need you around here. Ready to end some robot lives?"},
            {"POLICE003", "Always sir."},
            {"POLICE004", "Good to hear. Because they are causing more ruckus."},
            {"POLICE005", "I'm here to solve that, sir."},
            {"POLICE006", "One gang is controlling one of the towers. You will clean it up."},
            {"POLICE007", "Intel says they are making a huge robot there. It could cause a lot of terror."},
            {"POLICE008", "We don't want that sir. I won't let innocent people get hurt by filthy robots."},
            {"POLICE009", "Here is the address. Clean it up, and destroy the terrorists, okay?"},
            {"POLICE010", "Understood, sir."},
            {"POLICE011", "You must come dine with us sometime, kid."},
            {"POLICE012", "My wife cooks the best meatballs in town."},
            {"POLICE013", "I would love that, sir."},
            {"POLICE014", "This briefing is over. Lock and load."},

            {"POLICE015", "How did it go, kid?"},
            {"POLICE016", "It wasn't easy, sir. But it's all clear, sir. The big boss is no more."},
            {"POLICE017", "Great job, kid! I knew you had it in you!"},
            {"POLICE018", "Thank you, sir. I'm honored to be able to serve my community."},
            {"POLICE019", "OK. I have a new task for you already. But let's worry about that tomorrow. Now go rest."},
            {"POLICE020", "Thank you, sir!"},

            {"MOTHER018", "Hey mom!"},
            {"MOTHER019", "Oh geez! You scared me you little brat!"},
            {"MOTHER020", "Oh, sorry mom, I didn't mean to."},
            {"MOTHER021", "Oh good, you didn't mean to give me a heart attack. Well, ponder on that when I'm in my grave."},
            {"MOTHER022", "What? You are so scared you are dead now? Well, you talk an awful lot for a dead person, haha."},
            {"MOTHER023", "Why don't you just say it out loud? You want me to shut up and die, don't you? You unappreciative brat!"},
            {"MOTHER024", "Whoa whoa, no mom, why would I want that? I thought we were joking around."},
            {"MOTHER025", "Hahaha stupid, I played you, stupid. You are so stupid."},
            {"MOTHER026", "OK mom."},
            {"MOTHER027", "Let this be a lesson to you. It's really easy to scare an old lady. So don't sneak up on them."},
            {"MOTHER028", "OK."},
            {"MOTHER029", "Now, let's get to business. Where is my cocaine at?"},
            {"MOTHER030", "If you used cocaine you wouldn't call it cocaine."},
            {"MOTHER031", "My crack. My stash. My muse. Gimme gimme gimme."},
            {"MOTHER032", "Sorry mom, didn't bring you cocaine."},
            {"MOTHER033", "Son, you are a disgrace to this family."},
            {"MOTHER034", "OK mom."},
            {"MOTHER035", "You are a disappointment. You happened because of a broken condom. I should have aborted you."},
            {"MOTHER036", "Holy shit mom!"},
            {"MOTHER037", "OK OK just kidding around, don't get all defensive now."},
            {"MOTHER038", "I know, it's kind of your style to think mentioning broken condoms to your son is funny."},
            {"MOTHER039", "You know why I think that?"},
            {"MOTHER040", "Why?"},
            {"MOTHER041", "Because it IS funny."},
            {"MOTHER042", "OK mom. Good talk. I'm gonna head out now."},
            {"MOTHER043", "OK. Come back tomorrow, or I'll travel back in time just to abort you."},
            {"MOTHER044", "Love you mom."},
            {"MOTHER045", "Love you, too, honeyboo."},

            {"POLICE021", "Hey, are you back already?"},
            {"POLICE022", "Ready to rock and roll, sir."},
            {"POLICE023", "You know we are not musicians, right?"},
            {"POLICE024", "Yes, sir."},
            {"POLICE025", "Is that some kind of youngster talk that I don't understand?"},
            {"POLICE026", "Possibly, sir."},
            {"POLICE027", "I guess I will look it up on the world wide web tonight."},
            {"POLICE028", "Good idea, sir."},
            {"POLICE029", "OK. Are you ready for your next task?"},
            {"POLICE030", "Yes, sir. Let's kill some robots."},
            {"POLICE031", "That's exactly what I want you to do! Haha! How did you know?"},
            {"POLICE032", "Just made an educated guess, sir."},
            {"POLICE033", "Well that was a good guess, kid. These robots, they are controling another tower in the neighbourhood."},
            {"POLICE034", "And they are building another one of those big scary robots."},
            {"POLICE035", "Let's go in and clean the place up, a little bit, shall we? Show them some justice."},
            {"POLICE036", "Let's show them the consequences of choosing to be terrorists, sir."},
            {"POLICE037", "I like the way you are thinking, kid. Go handle it."},
            {"POLICE038", "Understood. I'll be on my way now, sir."},
            {"POLICE039", "Godspeed."},

            {"SALESPERSON000", "Hey baby."},
            {"SALESPERSON001", "Hello dear salesperson. Do you have some milk for me?"},
            {"SALESPERSON002", "Yes of course baby, anything for you. Same as usual?"},
            {"SALESPERSON003", "Yes, that sounds like a fruitful transaction."},
            {"SALESPERSON004", "Since this is a game, I should remind you. This milk lets you fire faster. The more you buy the faster you fire your weapon."},
            {"SALESPERSON005", "The price is 300 per cup. What do you say, want to buy?"},

            {"SALESPERSON006", "Babe, I missed you!"},
            {"SALESPERSON007", "Hi, yes, I'm here."},
            {"SALESPERSON008", "I have some rice with chicken. This will give you a shield. So if anyone hurts you, you won't die instantly."},
            {"SALESPERSON009", "What a good offer from a respectable salesperson."},
            {"SALESPERSON010", "One plate is for 100. Sound good?"},

            {"CAT000", "meow?"},
            {"CAT001", "You are a good kitty. I love you."},
            {"CAT002", "meow."},

            {"NOT_ENOUGH_MONEY", "(Not enough money)"},
            {"OUT_OF_STOCK", "(Out of stock)"},
            {"ACCEPT", "Accept"},
            {"DECLINE", "Decline"},
            {"START", "Start"},
            {"CONTINUE", "Continue"},
            {"NEW_GAME", "Start From Beginning"},

            {"POLICE040", "Sir, are you alright?"},
            {"POLICE041", "Kid! Is that you? My chair fell down and I can't get up!"},
            {"POLICE042", "Let me help you, sir. It's going to be alright."},
            {"POLICE043", "No, no, I'm too heavy! Don't worry, help is coming. The new girl is bringing some people."},
            {"POLICE044", "New girl?"},
            {"POLICE045", "Yes, we have a new police officer, she'll be helping us with the gang cases."},
            {"POLICE046", "Oh okay, that's nice."},
            {"POLICE047", "Yes. She is great. I like her more than you already. Haha! Just kidding kid!"},
            {"POLICE048", "That's funny, sir. Are you sure you are okay? I can try to help you."},
            {"POLICE049", "No no, it's fine. I'm enjoying this, actually. I've never looked at the ceiling of this room before. Did you know there are spiders here?"},
            {"POLICE050", "Yes, sir. They are everywhere in this office."},
            {"POLICE051", "Is that so? Okay. You can go now. We'll do the briefing tomorrow."},
            {"POLICE052", "See you, sir."},

            {"GIRL000", "Hey, are you the new girl?"},
            {"GIRL001", "I guess so. I am a girl and I am new."},
            {"GIRL002", "Cool."},
            {"GIRL003", "Cool?"},
            {"GIRL004", "Cool, cool."},
            {"GIRL005", "Cool."},
            {"GIRL006", "You know about the chief falling over?"},
            {"GIRL007", "Yeah, I am supposed to get help for him, but for now I am just enjoying laughing at him."},
            {"GIRL008", "Right."},
            {"GIRL009", "Right?"},
            {"GIRL010", "Right."},
            {"GIRL011", "OK."},
            {"GIRL012", "I'll be on my way now."},
            {"GIRL013", "Okay, take care!"},
            {"GIRL014", "Right."},

            {"MOTHER046", "Hello officer, did you make the world a better place yet?"},
            {"MOTHER047", "Hey mom. You are charming as ever."},
            {"MOTHER048", "Oh officer, please save us."},
            {"MOTHER049", "Comedy gold."},
            {"MOTHER050", "Oh officer, I am an old lady, I can't open this jar, please help me."},
            {"MOTHER051", "I regret coming here today."},
            {"MOTHER052", "Okay okay I'm done. How are you my son?"},
            {"MOTHER053", "I just killed a giant robot monster. But listening to you talk is harder than killing that robot."},
            {"MOTHER054", "Giant robot? By yourself?"},
            {"MOTHER055", "Yeah, you'd think they'd assign more than one officer on a mission like this."},
            {"MOTHER056", "Well, there is a new girl. Maybe she can help me."},
            {"MOTHER057", "New girl?"},
            {"MOTHER058", "Yeah, I just had a weird talk with her."},
            {"MOTHER059", "Weird? How?"},
            {"MOTHER060", "Yeah, I mean, I don't know. She has a different vibe about her."},
            {"MOTHER061", "Ooooooooo. Is she pretty?"},
            {"MOTHER062", "What? No. I don't know. I didn't notice."},
            {"MOTHER063", "Ooooooooooooooooooooooooooooooooo."},
            {"MOTHER064", "Come on, stop it mom."},
            {"MOTHER065", "You should ask her out."},
            {"MOTHER066", "Okay, can we talk about something else?"},
            {"MOTHER067", "Do you want to talk about all the cocaine you owe me?"},
            {"MOTHER068", "I don't owe you cocaine."},
            {"MOTHER069", "I raised a son who became a police officer but he thinks his momma doesn't deserve just a little bit of cocaine."},
            {"MOTHER070", "..."},
            {"MOTHER071", "Come on, you must have so much cocaine laying around from all the gang busts."},
            {"MOTHER072", "I'll be on my way now."},
            {"MOTHER073", "On your way to bring my cocaine?"},
            {"MOTHER074", "Bye, mom."},

            {"POLICE053", "Kid! Look! I am straight up again! It feels great!"},
            {"POLICE054", "That's great, sir!"},
            {"POLICE055", "Yeah! I told you I'd be okay!"},
            {"POLICE056", "Okay, let's get to business. How did it go with the robots?"},
            {"POLICE057", "They are dealt with, sir. Cleaned the whole tower."},
            {"POLICE058", "Heck yes! That sounds like a success to me!"},
            {"POLICE059", "It is a success, sir."},
            {"POLICE060", "Yes, that's how it sounds like!"},
            {"POLICE061", "Okay. Do I have a new mission, sir?"},
            {"POLICE062", "Yes, indeed you do, kid! Another tower! It's the last one! Lots of robots. One big robot. The whole package."},
            {"POLICE063", "There is no end to these terrorists, are there, sir?"},
            {"POLICE064", "We keep at it and they'll be wiped out one day, kid."},
            {"POLICE065", "Good point, sir."},

            {"GIRL015", "Hey."},
            {"GIRL016", "Hey!"},
            {"GIRL017", "Hi, how are you?"},
            {"GIRL018", "I'm good! Second day at work. Let's see how it goes."},
            {"GIRL019", "So what are your responsibilities?"},
            {"GIRL020", "So far? Not much. I helped chief get up. I made some coffee for him."},
            {"GIRL021", "I think you shouldn't make coffee because you are a woman."},
            {"GIRL022", "Do you mean women should not make coffee?"},
            {"GIRL023", "No, I mean, girls shouldn't make coffee for others just because they are women. Feminism and that, right?"},
            {"GIRL024", "Right. Feminism."},
            {"GIRL025", "Right."},
            {"GIRL026", "Sounds like you know your way around feminist literature."},
            {"GIRL027", "No, I just watched a video on facebook."},
            {"GIRL028", "Yeah, I figured."},
            {"GIRL029", "Okay. I'm gonna go kill some robots now."},
            {"GIRL030", "Kill them robots."},
            {"GIRL031", "That's the plan."},
            {"GIRL032", "See ya!"},

            {"POLICE066", "Kid, look! I fell down again! Hahaha!"},
            {"POLICE067", "Do you want help, sir?"},
            {"POLICE068", "No! Tell me about the tower!"},
            {"POLICE069", "There was a huge robot and I just fired at it until it went boom!"},
            {"POLICE070", "Sounds like an amazing adventure, kid!"},
            {"POLICE071", "It kind of was, sir."},
            {"POLICE072", "I hope we have many more adventures together, kid!"},
            {"POLICE073", "I hope so, too, sir. Thanks for trusting in me."},
            {"POLICE074", "Thanks for doing everything I tell you without questioning whatsoever!"},

            {"GIRL033", "Oh geez, are you okay? I think you just fell down a building."},
            {"GIRL034", "Yeah, I'm fine. There is no fall damage."},
            {"GIRL035", "Fall damage?"},
            {"GIRL036", "Yeah."},
            {"GIRL037", "Okay."},
            {"GIRL038", "Anyway."},
            {"GIRL039", "I'm gonna go now."},
            {"GIRL040", "Okay. See you!"},

            {"MOTHER075", "MY SON!"},
            {"MOTHER076", "Hey mom, what's up?"},
            {"MOTHER077", "Did you bring me my cocaine?"},
            {"MOTHER078", "No, mom."},
            {"MOTHER079", "Oh well, I love you anyway."},
            {"MOTHER080", "Love you, too, mom."},
            {"MOTHER081", "You are my favourite child."},
            {"MOTHER082", "I am an only child, mom."},
            {"MOTHER083", "Oh right, that's why."},
            {"MOTHER084", "You can just assume that I'm not hiding any siblings from you."},
            {"MOTHER085", "Why would you ever do something like that though?"},
            {"MOTHER086", "Exactly."},
            {"MOTHER087", "Exactly?"},
            {"MOTHER088", "Exactly."},

            {"THE_END", "The End"},
            {"THANKS_FOR_PLAYING", "Thanks for playing!"},
            {"CREDITS", "Credits"},
            {"QUIT", "Quit"},
            {"GAME_BY", "Game By:"},
            {"BACKGROUND_BY", "Background 3D Models:"},
        });
        errorSet = new HashSet<string>();
    }
    
    public static string Get(string key) {
        if (all[lang].ContainsKey(key)) {
            return all[lang][key];
        }
        else {
            if (!errorSet.Contains(key)) {
                errorSet.Add(key);
                UnityEngine.Debug.LogWarningFormat("Localization key not found: {0}", key);
            }
            return key;
        }
    }
}
